#!groovy
// Check ub1 properties
properties([disableConcurrentBuilds()])

pipeline {
    agent { 
        label 'master'  //собирает на ветке мастер  
        }
    options {
        buildDiscarder(logRotator(numToKeepStr: '10', artifactNumToKeepStr: '10')) // логи и артефакты последних 10 сборок
        timestamps()  
    }
    stages {
        stage("First step") {
            steps {
                sh 'echo \'hostname\''
            }
        }
        stage("Second step") {
            steps {
                sh 'ssh root@ub1 \'uptime\''
            }
        }
    }
}















// pipeline {
//   agent any
//   options {
//     buildDiscarder(logRotator(numToKeepStr: '5'))
//   }
//   environment {
//     DOCKERHUB_CREDENTIALS = credentials('dockerhub')
//   }
//   stages {
//     stage('Build') { // сборка
//       steps {
//         sh 'docker build -t lloydmatereke/jenkins-docker-hub .'
//       }
//     }
//     stage('Login') {  //логин в докерхаб
//       steps {
//         sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
//       }
//     }
//     stage('Push') {  // пуш образа
//       steps {
//         sh 'docker push lloydmatereke/jenkins-docker-hub'
//       }
//     }
//     stage('Deploy') {  // запуск приложухи
//       steps {
//         sh 'docker run --rm -p 5000:5000 lloydmatereke/jenkins-docker-hub '
//       }
//     }
//   }
//   post {
//     always {
//       sh 'docker logout'
//     }
//   }
// }